package compilador.generated;

import java_cup.runtime.*;

parser code {:
    //Errores
:};

//  ===== Terminales =====

// Lit y Identificadores
terminal String LIT_INT, LIT_FLOAT, LIT_CHAR, LIT_STRING;
terminal String ID;

// Tipos
terminal INT, FLOAT, BOOL, CHAR, STRING;

// Reservados
terminal VAL, READ, WRITE;
terminal RETURN, BREAK;
terminal IF, ELIF, ELSE, WHILE, FOR;
terminal VOID, PRINCIPAL;

// Delimitadores
terminal OPEN_LLAVES, CLOSE_LLAVES;
terminal OPEN_PAREN, CLOSE_PAREN;
terminal OPEN_BRACKET, CLOSE_BRACKET;
terminal FIN_SENTENCIA;
terminal COMA;

// Asignación
terminal ASIGN;

// Aritméticos
terminal OP_SUMA, OP_RESTA, OP_MULT;
terminal OP_DIV_DECIMAL, OP_DIV_ENTERA;
terminal OP_MODULO, OP_POTENCIA;
terminal OP_INCREMENTO, OP_DECREMENTO;

// Relacionales
terminal OP_MENOR, OP_MENOR_IGUAL;
terminal OP_MAYOR, OP_MAYOR_IGUAL;
terminal OP_IGUAL, OP_DIFERENTE;

// Lógicos
terminal OP_AND, OP_OR, OP_NEGACION;

// Booleanos
terminal TRUE, FALSE;

// ++++++ No terminales ++++++++


non terminal programa;
non terminal elemento_programa_cm;
non terminal elemento_programa;
non terminal funcion;
non terminal funcion_principal;
non terminal tipo_retorno;
non terminal lista_parametros;
non terminal var_simple;
non terminal tipo_var;
non terminal bloque;

// Declaraciones y asignaciones
non terminal declaracion_global;
non terminal creacion_simple;
non terminal creacion_asign;
non terminal asignacion;
non terminal creacion_arreglo;
non terminal asignacion_arreglo;
non terminal valores;
non terminal valor_asignable;

// Literales y accesos
non terminal literal;
non terminal literal_numerico;
non terminal acceso_arreglo;
non terminal indice;

// Sentencias
non terminal sentencia;
non terminal lista_sentencias;
non terminal sentencia_var;
non terminal sentencia_expr;
non terminal expr_incremento;

// Lectura, escritura y flujo de control simple
non terminal sent_read;
non terminal sent_write;
non terminal sent_return;
non terminal sent_break;
non terminal arg_read;
non terminal arg_write;
non terminal expr_retorno;

// expresiones Aritméticas
non terminal expr_primaria;
non terminal expr_negativo;
non terminal expr_potencia;
non terminal expr_aditiva;
non terminal expr_multiplicativa;
non terminal argumento_funcion;
non terminal lista_argumentos_funcion;
non terminal llamada_funcion;


// Placeholder para expresiones
non terminal expr_modulo;

start with programa;

// +_++++++++ Producciones ++++++++
tipo_retorno ::= INT
    | FLOAT
    | CHAR
    | BOOL;

tipo_var ::= INT
    | BOOL
    | FLOAT
    | STRING 
    | CHAR;

var_simple ::= tipo_var ID;

lista_parametros ::= var_simple COMA lista_parametros
    | var_simple;

bloque ::= OPEN_LLAVES lista_sentencias CLOSE_LLAVES;

funcion ::= tipo_retorno ID OPEN_PAREN lista_parametros CLOSE_PAREN bloque
    | tipo_retorno ID OPEN_PAREN CLOSE_PAREN bloque;

funcion_principal ::= VOID PRINCIPAL OPEN_PAREN CLOSE_PAREN bloque;

declaracion_global ::= creacion_simple
    | creacion_asign
    | creacion_arreglo;

elemento_programa ::= declaracion_global
    | funcion;

elemento_programa_cm ::= elemento_programa_cm elemento_programa
    | ;

programa ::= elemento_programa_cm funcion_principal elemento_programa_cm;

expr_retorno ::= expr_modulo;

expr_modulo ::= expr_modulo OP_MODULO expr_multiplicativa
    | expr_multiplicativa;

expr_multiplicativa ::= expr_multiplicativa OP_MULT expr_aditiva
    | expr_multiplicativa OP_DIV_DECIMAL expr_aditiva
    | expr_multiplicativa OP_DIV_ENTERA expr_aditiva
    | expr_aditiva;

expr_aditiva ::= expr_aditiva  OP_SUMA expr_potencia
    | expr_aditiva  OP_RESTA expr_potencia
    | expr_potencia;

expr_potencia ::= expr_negativo OP_POTENCIA expr_potencia
    | expr_negativo;

expr_negativo ::= OP_RESTA literal_numerico
    | expr_primaria;

expr_primaria ::= literal
    | ID
    | acceso_arreglo
    | llamada_funcion
    | OPEN_PAREN expr_modulo CLOSE_PAREN;


literal_numerico ::= LIT_INT
    | LIT_FLOAT;

argumento_funcion ::= expr_modulo;

lista_argumentos_funcion ::= argumento_funcion COMA lista_argumentos_funcion
    | argumento_funcion;

llamada_funcion ::= ID OPEN_PAREN lista_argumentos_funcion CLOSE_PAREN
    | ID OPEN_PAREN CLOSE_PAREN;



literal ::= literal_numerico
    | LIT_CHAR
    | LIT_STRING
    | TRUE
    | FALSE;

indice ::= ID
    | LIT_INT;

acceso_arreglo ::= ID OPEN_BRACKET indice CLOSE_BRACKET;

valor_asignable ::= expr_modulo;

creacion_simple ::= VAL var_simple FIN_SENTENCIA;

creacion_asign ::= VAL var_simple ASIGN valor_asignable FIN_SENTENCIA;

asignacion ::= ID ASIGN valor_asignable FIN_SENTENCIA;

creacion_arreglo ::= VAL var_simple ASIGN OPEN_LLAVES valores CLOSE_LLAVES FIN_SENTENCIA;

asignacion_arreglo ::= acceso_arreglo ASIGN valor_asignable FIN_SENTENCIA;

valores ::= literal_numerico COMA valores
    | literal_numerico;

sentencia_expr ::= expr_modulo FIN_SENTENCIA
    | expr_incremento FIN_SENTENCIA;

expr_incremento ::= ID OP_INCREMENTO
    | ID OP_DECREMENTO;

arg_read ::= ID;

arg_write ::= LIT_STRING
    | LIT_INT
    | LIT_FLOAT
    | TRUE
    | FALSE
    | ID;

sent_read ::= READ OPEN_PAREN arg_read CLOSE_PAREN FIN_SENTENCIA;

sent_write ::= WRITE OPEN_PAREN arg_write CLOSE_PAREN FIN_SENTENCIA;

sent_return ::= RETURN expr_retorno FIN_SENTENCIA
    | RETURN FIN_SENTENCIA;

sent_break ::= BREAK FIN_SENTENCIA;

sentencia_var ::= creacion_simple
    | creacion_asign
    | asignacion
    | creacion_arreglo
    | asignacion_arreglo
    | sentencia_expr;

sentencia ::= sentencia_var
    | sent_return
    | sent_break
    | sent_read
    | sent_write;

lista_sentencias ::= sentencia lista_sentencias
    | ;